### ISSUE TITLE
Texture won't show in the Preview panel

### ISSUE THREAD

**Issue by hoangtrung1999** [dfranx/SHADERed#234] opened 2021-07-12 05:42 UTC
![image](https://user-images.githubusercontent.com/12170169/125236573-6fd1cd80-e30e-11eb-9867-a46315f4faf8.png)
Hi, I'm trying to add a simple texture for my cube, but the preview shows it as a flat color, while the debugger show it correctly. What can I do to fix this?

**Comment by hoangtrung1999** [comment] 2021-07-12 05:52
I find out the problem was because of TANGENT & BINORMAL in the pixel shader input. How can I fix this?
![3](https://user-images.githubusercontent.com/12170169/125237489-f89d3900-e30f-11eb-8e58-193e736933fc.png)
![4](https://user-images.githubusercontent.com/12170169/125237494-f9ce6600-e30f-11eb-92f4-37894ce7bf0c.png)

**Comment by danilw** [comment] 2021-07-12 07:37
> How can I fix this?

Use Unity or Godot instead of SHADERed

SHADERed has way too many bugs, and absolutely not ready for "any" usage.

**Comment by dfranx** [comment] 2021-07-12 11:41
Hey @hoangtrung1999 ! I can't precisely diagnose the issue without seeing the whole project. Though, here are some things that could be the cause of this:
1. Make sure that you've properly defined the input layout (right click on your shader pass -> `Input layout`) and that the order in that window matches the order of the members in your vertex shader input structure.
2. Make sure that the order of the members in the vertex shader output structure matches the order of members in pixel shader input structure.

HLSL semantics aren't properly supported in SHADERed since SHADERed currently only has OpenGL backend and the compiler it uses to convert HLSL -> SPIR-V unfortunately doesn't output the semantic information.

I've gotten the same pixel shader to work, but as I said you just got to make sure that the order of output/input variables matches:

![image](https://user-images.githubusercontent.com/30801537/125281465-8aa84000-e316-11eb-8d7a-c873b25d0ba2.png)
![image](https://user-images.githubusercontent.com/30801537/125281496-93991180-e316-11eb-85d4-6d08eeb14e45.png)

@danilw pretty rude from you to come here and steer users away from SHADERed with your false claims rather than providing constructive criticism. If SHADERed has "too many bugs" please feel free to report those bugs and I'll gladly fix them immediately if they are really critical and make SHADERed "absolutely not ready for any usage". This wasn't even issue on my end and I'm pretty sure I've written somewhere in the docs/tutorials about this issue. Please refrain yourself from doing this in the future, thanks!

Closing!

**Closed by dfranx** 2021-07-12 11:41 UTC
