### ISSUE TITLE
Backspace jumps

### ISSUE THREAD

**Issue by Jlkam** [dfranx/SHADERed#77] opened 2020-03-04 21:58 UTC
Backspace deletes one char at the left and then it jumps three more chars to the left.
(Windows Version)

**Comment by Calinou** [comment] 2020-03-04 22:59
Duplicate of #68. It seems to only happen with HLSL shaders by the way.

**Comment by dfranx** [comment] 2020-03-05 19:40
I think it happens with GLSL shaders too. Not sure right now, but it was fixed. The fix will be included in the v1.3.1

**Closed** 2020-03-05 19:40 UTC
