### ISSUE TITLE
IDE force close after bad shader

### ISSUE THREAD

**Issue by SamLefebvre** [dfranx/SHADERed#56] opened 2020-02-25 18:07 UTC
I tried to modify the example cube and when I tried to save/render and the IDE force close without warning.
Where is the code I used : 
(I know the code is bad)

```
#version 330

in vec4 color;
out vec4 outColor;

void main() {
   outColor = vec4(color);
   outColor = vec3(color); // This crash the ide
}
```

Tested with version 1.3 and 1.24, 32 and 64 bits on Windows 10.
Here my log file 

[log.txt](https://github.com/dfranx/SHADERed/files/4251239/log.txt)

**Comment by dfranx** [comment] 2020-02-27 21:00
Unfortunately, I can't reproduce the bug.
Does this happen always? Would it happen even if you downloaded SHADERed again (and without modifying settings)?

**Comment by SamLefebvre** [comment] 2020-02-28 16:56
This happen always. In the windows diagnostic it is written that BEX64.exe has crashed. 
I have a AMD graphic card (RX 480), with the latest driver. Is SHADERed not compatible with amd cards ?
On my laptop, with a intel graphic, I have no problem.

**Comment by Trass3r** [comment] 2020-04-14 13:12
Definitely crashes on bad shader input like `const float f = 100 *;`. Which means continuous mode is unusable and opening a project with invalid shaders is not even possible.
The cause is an `invalid_argument` exception thrown somewhere in the exe. I could tell you where if debug symbols were available for the releases.

**Comment by dfranx** [comment] 2020-04-14 14:46
@Trass3r @SamLefebvre This should be fixed with the PR #91 . The fix will be included in the v1.3.3 release. The problem was in error message parsing for AMD cards - std::stoi would throw an exception. Closing.

**Closed by dfranx** 2020-04-14 14:46 UTC

**Comment by Trass3r** [comment] 2020-04-14 14:50
Thanks, in my case it's an Intel iGPU though, just fyi.

**Comment by dfranx** [comment] 2020-04-14 15:03
Interesting.. Well, in v1.3.3 it shouldn't crash anymore but it won't show line number at which the error happens. Not sure how to handle that though, different drivers == different error messages I guess.

Also, I guess I could start providing debug symbols starting from the next release.

**Comment by SamLefebvre** [comment] 2020-04-14 15:06
Thank you.

**Comment by Trass3r** [comment] 2020-04-14 15:13
Maybe glslang could help. Isn't that needed for SPIRV-VM anyway?

**Comment by dfranx** [comment] 2020-04-15 18:23
Yes, glslang is needed for SPIRV-VM. I love this idea and will most likely do it this way.  This will also be great if I decide to add Vulkan backend one day.
I'll have to thoroughly test this though, don't want to break something.
