### ISSUE TITLE
Sound Shaders 

### ISSUE THREAD

**Issue by Bellbirdbits** [dfranx/SHADERed#184] opened 2021-02-22 03:19 UTC
I'm currently unable to run sound shaders in SHADERed, both on desktop (AMD) and laptop (Intel surface pro), OS is win10 pro. A burst of noise is heard during initialise and SHADERed no long outputs sound after that.

**Comment by dfranx** [comment] 2021-02-22 14:20
Thanks for reporting!
I currently can't reproduce this issue on my machine but I plan to update that part of SHADERed anyway at some point in the near future (I want to switch from SFML's audio library to miniaudio before relase of v1.6) so I might fix it along the way. Currently I have no idea what's causing this issue.

**Comment by dfranx** [comment] 2021-06-06 14:36
I believe that this should be fixed with one of the recent updates (I switched from SFML to miniaudio).

**Closed by dfranx** 2021-06-06 14:36 UTC
