### ISSUE TITLE
Moving loaded model on viewport crashes application

### ISSUE THREAD

**Issue by ooploopl-** [dfranx/SHADERed#18] opened 2019-09-04 06:20 UTC
[SHADERed v1.1.3](https://github.com/dfranx/SHADERed/releases/tag/v1.1.3) Win64
As stated in title, a simple obj file below i can reproduce the crash with it.
[icosphere.zip](https://github.com/dfranx/SHADERed/files/3572961/icosphere.zip)

**Comment by dfranx** [comment] 2019-09-04 10:53
Thanks for reporting! Looking more into it right now! It also crashes on my PC before I even load it. Probably because material file is missing. If I remove mtllib line it loads fine but crashes on selection.

But anyway, working on a fix for both things. Thanks for providing the model too, makes it easier to find bugs!

**Comment by dfranx** [comment] 2019-09-04 15:06
Thanks again for reporting, I have fixed it! The fix will come with the version 1.1.4

**Comment by dfranx** [comment] 2019-09-11 13:51
Hey @ooploopl- !

I've just pushed a release that includes a fix for this bug. Could you try testing again and see if it works now?

**Comment by ooploopl-** [comment] 2019-09-11 14:21
Hello there, it doesn't work for me. Crashing right away when trying to load. I also tried keeping vertex order, writing polygroups, exporting as group or/and as object.

**Comment by dfranx** [comment] 2019-09-11 14:39
That is so weird... Works fine here...
![screenshot](https://user-images.githubusercontent.com/30801537/64706855-75f88800-d4b2-11e9-8310-9cd076e5c687.jpg)

I'll try to push a hotfix as soon as I find what the problem is...

**Comment by ooploopl-** [comment] 2019-09-11 16:00
I'm using extact model, also tried several other, all resulted same type of crash.

**Comment by dfranx** [comment] 2019-09-14 13:05
Hey @ooploopl- !
Could you please download the v1.1.5 and do the following steps:
1. Turn on the "Stream logs" option (Options -> General -> Stream logs)
2. Restart SHADERed
3. First, try to load the examples/features/model project. If it crashes, send me the log.
4. If the previous step works fine then try to add your own 3D model provided here and then send me the log.

Also, what OpenGL version does your GPU support?

**Comment by ooploopl-** [comment] 2019-09-15 10:49
Hello @dfranx ,
"examples/features/model" project loads without any error.
Model i provided crashes, log is below.
My gpu supports OpenGL 4.6.
[log.txt](https://github.com/dfranx/SHADERed/files/3613655/log.txt)

**Comment by ooploopl-** [comment] 2019-09-15 10:50
And here is log for another model, exactly same error.
[log.txt](https://github.com/dfranx/SHADERed/files/3613659/log.txt)

**Comment by dfranx** [comment] 2019-09-15 12:26
Thanks for the logs.
It seems like you are not properly openning your 3D model file.
The message "Loading a 3D model D:/Apps/SHADERed/templates/GLSL/" tells me that you haven't properly selected a file (there is no file name and extension after ./GLSL/).

AFAIK, this shouldn't be possible with the file dialog. Are you manually entering the 3D model location? Also, what version of Windows are you using?

**Comment by ooploopl-** [comment] 2019-09-15 15:09
I'm not manually entering. It literally crashes right after i select the file from dialog. I'm including a small video for you to review how i try to load the model.
[crash_view](https://paste.xinu.at/tK1)
Windows 10 Enterprise N LTSC
Version 1809
OS Build: 17763.737

**Comment by dfranx** [comment] 2019-09-15 15:34
Okay! That bug is definitely weird... I've tested SHADERed on few different PCs and your 3D model worked normally. But I will look more into and try to find the cause of this problem.
Also, thank you so much for the detailed info.

**Comment by ooploopl-** [comment] 2019-09-15 15:39
I just found the bug, if file is on different drive e.g application sitting on D:\ drive and model was located on C:\. I tried moving my model to the same drive application located and it loads without any problem.

**Comment by dfranx** [comment] 2019-09-15 16:32
Thanks so much for the help! I've pushed a commit that should fix this problem. The binary version will probably come out in a week or so. I will leave this issue open until then.

Thank you once again!

**Comment by ooploopl-** [comment] 2019-09-15 17:00
Your welcome, thanks for your hard work.

**Comment by dfranx** [comment] 2019-09-17 12:02
Hey! I've just released binaries for v1.2 which includes a fix for this.. Could you confirm that it works now?

**Comment by ooploopl-** [comment] 2019-09-17 14:32
Hello, yes issue is resolved, works as expected. Thank you! 🎉

**Comment by dfranx** [comment] 2019-09-17 14:47
Nice! No problem! Closing

**Closed by dfranx** 2019-09-17 14:47 UTC
